name: build
on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: MinGW Winlibs
        uses: Denzy7/action-mingw@v0.1
            
      - name: 设置环境变量
        run:
          set path=%path%;c:\mingw64\bin
          

      - name: install dependencies
        shell: bash
        run: python -m pip install -r requirements.txt

      - name: build main.py
        shell: bash
        run: |
          python -m nuitka \
            --standalone \
            --assume-yes-for-downloads \
            --follow-imports \
            --no-prefer-source-code \
            main.py

      - name: test main.exe
        shell: bash
        working-directory: main.dist
        run: ./main.exe
