name: build
on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: 下载 MinGW
        shell: pwsh
        run: Invoke-WebRequest https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-18.1.8-12.0.0-ucrt-r1/winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-18.1.8-mingw-w64ucrt-12.0.0-r1.zip -OutFile C:\mingw64.zip
            
      - name: 解压并设置环境变量
        run: |
          tar -xf C:\mingw64.zip
          set path=%path%;C:\mingw64\bin
          

      - name: install dependencies
        shell: bash
        run: python -m pip install -r requirements.txt

      - name: build main.py
        shell: bash
        run: |
          python -m nuitka \
            --standalone \
            --assume-yes-for-downloads \
            --follow-imports \
            --no-prefer-source-code \
            main.py

      - name: test main.exe
        shell: bash
        working-directory: main.dist
        run: ./main.exe
