name: build
on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: 下载 MinGW
        shell: pwsh
        run: Invoke-WebRequest https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-19.1.1-12.0.0-msvcrt-r2/winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.1-mingw-w64msvcrt-12.0.0-r2.zip -OutFile C:\mingw64.zip
            
      - name: 解压
        run: 
          tar -xf C:\mingw64.zip -C C:\
      - name: 环境变量
        run: setx PATH "%PATH%;C:\mingw64\bin" /M

      - name: install dependencies
        shell: bash
        run: python -m pip install -r requirements.txt

      - name: 编译 main.py
        run:
          python -m nuitka -mingw64 --standalone --onefile --assume-yes-for-downloads --follow-imports --no-prefer-source-code --main="main.py"

      - name: test main.exe
        shell: bash
        working-directory: main.dist
        run: ./main.exe
